spring:
  servlet:
    multipart:
      max-file-size: 10MB # 设置单个文件的大小为10M
  data:
    mongodb:
      uri: mongodb://localhost:27017/product_paper_content_vj
  redis:
    database: 0
    host: localhost
    port: 6379


server:
  tomcat:
    max-http-header-size: 8192
  port: 8082

config:
  storePath: "materialLib"

api-credentials: "src/main/resources/pdfservices-api-credentials.json"


